version: "3.8"
name: graphql-api
services:
  minio:
    image: minio/minio
    command: ["server", "--console-address", ":9001", "/data"]
    restart: always
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - gqlapi

networks:
  gqlapi:
